---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekart-deployment
  labels:
    app: ekart
spec:
  replicas: 2
  selector:
      matchLables:
        app: ekart
  template:
    metadata:
      labels:
        app: ekart
    spec:
      containers:
      - name: ekart
        image: pavan73384/ekart:latest
        ports:
        - containerPort: 8070 
---
apiVersion: v1
kind: Service
metadata:
  name: ekart-service
spec:
  type: LoadBalancer
  selector:
    app: ekart
  ports:
  - protocol: TCP
    port: 8070
    targetPort: 8070
